Campaign urls (Raw redirects)
amazeeio-solutions/silverback-mono pull request #1369
Opened 2023-06-06 06:36 UTC by chindris

## Package(s) involved

silverback_raw_redirect

## Description of changes

This PR introduces a new entity type, called **Raw Redirect**. The backend administrators will be able to create these raw redirects, meaning that they are free to input any kind of source and destination paths. There's no domain or language check on them. These redirects can then be sourced into the Gatsby app for example and from there they can be exported as redirects for the different hosting providers (for example for Netlify). An example on how to do this was added in the gatsby-node.ts file of the silverback-gatsby app.

The entry point for administering the raw redirects (in the backend) is /admin/config/search/raw_redirect . From there, people with the **Administer individual raw URL redirects** permission are able to add / edit /delete these redirects.

## Related Issue(s)

https://github.com/AmazeeLabs/silverback-mono/issues/1349

## How has this been tested?

Locally, manually.

2023-06-06 08:34 UTC, chindris commented on apps/silverback-gatsby/gatsby-node.ts
> +import { GatsbyNode } from 'gatsby';
@pmelab  should this be extracted maybe in a separate package? It would be easier to use it afterwards in the other apps.

2023-06-07 11:48 UTC, pmelab commented on apps/silverback-gatsby/gatsby-node.ts
> +import { GatsbyNode } from 'gatsby';
Yes. As already discussed we could add a schema extension to the Drupal module that provides the GraphQL type, and Gatsby plugin that executes the query and creates the redirects.

The latter could also be added to `gatsby-source-silverback` 🤔 , so we don't need another plugin. It just has gracefully handle the case when the schema extension is not active. But that information should be in the `FeedInfo`.

2023-06-07 11:49 UTC, pmelab requested changes
The module should actually be called `silverback_campaign_urls`. And as discussed in another comment, we can make the remaining Drupal and Gatsby parts reusable as well.

2023-06-11 07:46 UTC, chindris commented on apps/silverback-gatsby/gatsby-node.ts
> +import { GatsbyNode } from 'gatsby';
Hi @pmelab !

This is now in the `gatsby-source-silverback` package. The `CampaignUrl` entities will generate redirects if the schema extension is enabled in Drupal.

2023-06-11 07:46 UTC, chindris commented
> The module should actually be called `silverback_campaign_urls`. And as discussed in another comment, we can make the remaining Drupal and Gatsby parts reusable as well.

The module name has been changed to `silverback_campaign_urls`.

2023-06-13 03:56 UTC, pmelab approved these changes
Great! 😊 
I just realized that we should also be able to manage splat rewrites (`/blog/* https://old-blog.com/:splat`) with this 🤯

2023-06-13 05:55 UTC, chindris commented
> Great! 😊 I just realized that we should also be able to manage splat rewrites (`/blog/* https://old-blog.com/:splat`) with this 🤯

yes, we can input any source and destination string for the urls, like we'd directly edit the redirects file

2023-06-13 05:56 UTC, merged