Entity usage plugin for media references in Gutenberg
amazeeio-solutions/silverback-mono pull request #970
Opened 2022-03-02 15:31 UTC by chindris

## Package(s) involved

silverback_gutenberg

## Description of changes

Adds en Entity Usage plugin for media embedded in Gutenberg.

## Related Issue(s)

[Create Gutenberg plugin for Entity Usage module](https://github.com/AmazeeLabs/silverback-mono/issues/827)

## How has this been tested?

Locally, manual.

2022-03-02 16:06 UTC, pmelab requested changes
Thanks! The implementation looks on point. But I think we should have a basic test that makes sure it still works. When for example the block parser changes and its not called `mediaEntityIds` any more.

Here are the other tests implement by @Leksat :
https://github.com/AmazeeLabs/silverback-mono/tree/development/packages/tests/silverback-gutenberg/playwright-tests

2022-03-07 06:29 UTC, chindris commented
> Thanks! The implementation looks on point. But I think we should have a basic test that makes sure it still works. When for example the block parser changes and its not called `mediaEntityIds` any more.
> 
> Here are the other tests implement by @Leksat : https://github.com/AmazeeLabs/silverback-mono/tree/development/packages/tests/silverback-gutenberg/playwright-tests

Hi @pmelab !
I added a set of playwright tests and also updated the silverback-drupal app to contain the entity usage module.

2022-03-07 07:54 UTC, pmelab approved these changes

2022-03-07 07:55 UTC, pmelab commented
Awesome! Thanks @chindris !

2022-03-07 14:40 UTC, Leksat approved these changes

2022-03-08 13:31 UTC, merged